### ISSUE TITLE
There's a glitch. When you click on the password protected page, sometimes, half of the page is not displayed properly. Attached is a picture

### ISSUE THREAD

**Issue by peterhaddad98** [MaxLaumeister/clientside-html-password#1]
![password protected](https://cloud.githubusercontent.com/assets/26935752/26384242/daf751b2-4005-11e7-9bab-25908b7018c2.PNG)

**Comment by MaxLaumeister** [comment]
Thank you for the bug report! I was not able to reproduce this bug on my computers though. It looks like a graphics card glitch to me, and part of what makes me think that is that the main page and demo page are separate code-wise, so when you click the live demo button, the browser navigates to the demo page and unloads the main page completely, so none of it should be showing anymore. I would bet that the glitch is specific to your computer/graphics card. Disabling hardware acceleration in Chrome may fix the issue. Good luck!
