### ISSUE TITLE
Would be nice if it worked on a node html page.

### ISSUE THREAD

**Issue by rayj00** [MaxLaumeister/clientside-html-password#2]
So I have a nodejs page that I'd like to pw protect but ran into your clientside app.  It works fine for the
initial page access, however  for subsequent page access, the page does not work as designed.

So initially, an authorized user on a website wants to start a video conference.  he clicks the links and 
starts the WebRTC conference.   He texts or provides a unique link to the attendees of the conference.
However, when an attendee browses the link, he encounters your password app,  but after entering the password,  it's like the attendee is initializing his own conference instead of joining the existing one.

I know this is probably beyond the scope of your app,  but it would be nice to have.  I guess I could modify the code perhaps?

Good job though....

Ray

**Comment by MaxLaumeister** [comment]
Hi Ray!

Please do feel free to modify the code - this project is MIT licensed after all! You probably could see this coming, but yeah this is beyond the scope of the app. The app is designed to encrypt static HTML pages only, and it would require a major redesign to get it to integrate with dynamic pages served by nodejs. If you do decide to integrate nodejs support then good luck to you!

Oh and as a note, if you are using nodejs you probably don't need my code or even page encryption at all - [HTTP basic auth](https://www.npmjs.com/package/basic-auth) should work quite well.
