### ISSUE TITLE
Stronger encryption?

### ISSUE THREAD

**Issue by infracritical** [MaxLaumeister/clientside-html-password#6]
Does your encryption library that you (and staticrypt) use allow for larger encryption keys? The reason for this inquiry is to develop self-destruct web pages after (n) times of viewing.

Would love your thoughts on the matter.  Email at your discretion.

**Comment by MaxLaumeister** [comment]
Hi infracritical,

Unfortunately, it is not possible to have client-side code that cryptographically self-destructs after (n) times of viewing. It is not something that cryptography can do.

The only solution is to use server-side code. If you want to pursue that solution then I wish you luck, but it is beyond the scope of this project. If you would like to re-use code from this project, note that it's already using a 256-bit AES key length, which is extremely strong and industry standard. Please tell me if you have any questions!
